import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Mystic Tarot",
  description: "Terms of Service for Mystic Tarot. Please read these terms carefully before using our services.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 animate-fadeIn">
      <h1 className="text-3xl font-bold text-mystic-100 mb-8">Terms of Service</h1>
      <div className="prose prose-invert max-w-none space-y-6 text-mystic-200">
        <p className="text-sm text-mystic-500">Last updated: June 22, 2026</p>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">1. Acceptance of Terms</h2>
          <p>By accessing and using Mystic Tarot (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">2. Service Description</h2>
          <p>Mystic Tarot provides AI-generated tarot card readings for entertainment and personal reflection purposes. The readings are generated by artificial intelligence and should not be considered professional advice.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">3. Entertainment Purposes Only</h2>
          <p>All tarot readings provided by the Service are for <strong>entertainment purposes only</strong>. The readings should not be used as a substitute for professional medical, legal, financial, or psychological advice. You are responsible for your own decisions and actions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">4. User Responsibilities</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>You must be at least 18 years old to use paid services</li>
            <li>You agree not to misuse the Service or attempt to circumvent payment</li>
            <li>You are responsible for maintaining the confidentiality of your account</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">5. Payments &amp; Refunds</h2>
          <p>All payments are processed securely by Creem. Prices are clearly displayed before purchase. Refund requests are handled on a case-by-case basis. Since readings are digital, AI-generated content, refunds are generally not provided after the reading is delivered.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">6. Intellectual Property</h2>
          <p>The Service, including its design, text, and AI-generated readings, is the property of Mystic Tarot. You may not reproduce, distribute, or create derivative works without our consent.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">7. Limitation of Liability</h2>
          <p>Mystic Tarot shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. The Service is provided &ldquo;as is&rdquo; without warranty of any kind.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-mystic-100 mt-8 mb-3">8. Contact</h2>
          <p>For questions about these Terms, contact us at <a href="mailto:support@mystictarot.app" className="text-mystic-400 hover:text-mystic-300">support@mystictarot.app</a>.</p>
        </section>
      </div>
    </div>
  );
}
